name = "otp-service"
main = "worker.js"
compatibility_date = "2025-04-01"

[vars]
APP_ENV = "production"
WABA_NUMBER = "6285155330089"
TELEGRAM_BOT = "fdv_devbot"

[[d1_databases]]
binding = "DB"
database_name = "otp-db"
database_id = "3ea66fec-3c64-4916-9ec5-69aaabd93e32"

[observability]
[observability.logs]
enabled = true
invocation_logs = true